### ISSUE TITLE
GitHub description misspelling

### ISSUE THREAD

**Issue by saltedcoffii** [synodriver/python-bz3#4]
The GitHub description has a typo, it says "python bingding for bzip3"; I imagine it's supposed to say "python binding for bzip3" or "python bindings for bzip3"

![image](https://user-images.githubusercontent.com/55339220/196034420-9a954af5-e905-4c00-9732-388e1a66522d.png)

**Comment by synodriver** [comment]
Oh, I see it, thinks for reporting it.

**Comment by synodriver** [comment]
fixed
